#!/bin/bash
# DOCKER_DEFAULT_PLATFORM=linux/amd64 \
# devcontainer features test \
#   --project-folder . \
#   --features android-sdk \
#   --filter host_sdk \
#   --skip-autogenerated \
#   --skip-duplicated
set -e

source dev-container-features-test-lib

check "container sdkmanager is installed" bash -c "sdkmanager --version"
check "container adb is installed" bash -c "adb --version"
check "host platform is installed" bash -c "sdkmanager --sdk_root=/opt/android-host-sdk --list_installed | grep -q 'platforms;android-36'"
check "host build tools are installed" bash -c "sdkmanager --sdk_root=/opt/android-host-sdk --list_installed | grep -q 'build-tools;36.0.0'"
check "host platform tools are installed" bash -c "sdkmanager --sdk_root=/opt/android-host-sdk --list_installed | grep -q 'platform-tools'"

reportResults