#!/bin/bash
# DOCKER_DEFAULT_PLATFORM=linux/amd64 \
# devcontainer features test \
#   --project-folder . \
#   --features android-sdk \
#   --filter specific_sdk \
#   --skip-autogenerated \
#   --skip-duplicated
set -e

source dev-container-features-test-lib

check "adb is installed in custom Android SDK directory" /opt/android-sdk/platform-tools/adb --version
check "custom Android platform is installed" bash -c "/opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --list_installed | grep -q 'platforms;android-34'"
check "custom build tools are installed" bash -c "/opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --list_installed | grep -q 'build-tools;34.0.0'"

reportResults
